logger:
  level: INFO

http:
  host: localhost
  port: 8080

storage:
  type: sql  # или "memory"

database:
  dsn: "host=localhost port=5432 user=calendar password=calendar dbname=calendar sslmode=disable"
